# Generated by Django 3.1.4 on 2021-05-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20210519_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
