# Generated by Django 3.1.4 on 2021-05-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
